/*1. Sa se afiseze doar studentii cu media cuprinsa intre 6.50 si 7.50.*/
SELECT *
FROM STUDENTI_ICA 
WHERE MEDIE_ANT BETWEEN 6.50 AND 7.50

/*2. Sa se afiseze cea mai mica si cea mai mare medie.*/
SELECT MIN(MEDIE_ANT) MINIM, MAX(MEDIE_ANT) MAXIM
FROM STUDENTI_ICA

/*3. Sa se afiseze nota medie pentru fiecare examen.*/
SELECT COD_EXAMEN, AVG(NOTA)
FROM EXAMENE_ICA
GROUP BY COD_EXAMEN

/*4. Sa se calculeze majorarea bursei daca:
-0.1% din valoarea ei daca e Bursa sociala
-0.2% din valoarea ei daca e Bursa de merit
-0.3% din valoarea ei daca e Bursa de studiu
-0.5% din valoarea ei daca e Bursa de performanta.*/
SELECT COD_BURSA, TIP_BURSA, MEDIE_MIN, VALOARE,
CASE
WHEN TIP_BURSA='Bursa sociala' THEN '0.1'
WHEN TIP_BURSA='Bursa de merit' THEN '0.2'
WHEN TIP_BURSA='Bursa de studiu' THEN '0.3'
WHEN TIP_BURSA='Bursa de performanta(olimpici)' THEN '0.5'
ELSE '-'
END AS "MAJORARE"
FROM BURSE_ICA

/*5.Sa se afiseze numele si prenumele studentilor care beneficiaza de bursa precum si tipul si valoarea acesteia.*/
SELECT STUDENTI_ICA.NUME, STUDENTI_ICA.PRENUME, BURSE_ICA.TIP_BURSA, BURSE_ICA.VALOARE
FROM STUDENTI_ICA
INNER JOIN BURSE_ICA ON STUDENTI_ICA.COD_BURSA=BURSE_ICA.COD_BURSA;

/*6.Sa se afiseze toti studenti care au dat examene.*/
SELECT STUDENTI_ICA.NUME, STUDENTI_ICA.PRENUME, EXAMENE_ICA.DATA, EXAMENE_ICA.NOTA
FROM EXAMENE_ICA
FULL OUTER JOIN STUDENTI_ICA ON EXAMENE_ICA.NR_MATRICOL=STUDENTI_ICA.NR_MATRICOL;

/*7. Sa se afiseze toate examenele (distincte).*/
SELECT DISTINCT COD_EXAMEN,DATA, COD_MATERIE
FROM EXAMENE_ICA

/*8.Sa se afiseze toti studentii picati la examene.*/
SELECT s.NUME, s.PRENUME, m.DENUMIRE, e.DATA, e.NOTA
FROM EXAMENE_ICA e, STUDENTI_ICA s, MATERII_ICA m
WHERE e.NOTA<=5 AND e.NR_MATRICOL=s.NR_MATRICOL AND m.COD_MATERIE=e.COD_MATERIE

/*9. Sa se afiseze numele si codul disciplinei precum si profesorul care o preda. Ordonarea se va face dupa denumirea disciplinei.*/
SELECT m.COD_MATERIE, m.DENUMIRE, p.NUME_P, p.PRENUME_P
FROM MATERII_ICA m, PROFESORI_ICA p
WHERE m.COD_MATERIE=p.COD_MATERIE
ORDER BY DENUMIRE

/*10. Sa se afiseze numarul studentilor care beneficiaza de fiecare bursa.*/
SELECT BURSE_ICA.TIP_BURSA, COUNT(STUDENTI_ICA.NR_MATRICOL) AS NR_STUDENTI
FROM STUDENTI_ICA
INNER JOIN BURSE_ICA ON STUDENTI_ICA.COD_BURSA=BURSE_ICA.COD_BURSA
GROUP BY BURSE_ICA.TIP_BURSA

/*11. Sa se afiseze numele profesorilor, data si numele materiei la care se sustine examen.*/
SELECT DISTINCT PROFESORI_ICA.NUME_P, PROFESORI_ICA.PRENUME_P, MATERII_ICA.DENUMIRE, MATERII_ICA.AN, EXAMENE_ICA.DATA
FROM MATERII_ICA
INNER JOIN PROFESORI_ICA ON PROFESORI_ICA.COD_MATERIE = MATERII_ICA.COD_MATERIE
INNER JOIN EXAMENE_ICA ON EXAMENE_ICA.COD_MATERIE = MATERII_ICA.COD_MATERIE

/*12. Sa se afiseze profesorii si departamentele din care fac parte acestia.*/
SELECT PROFESORI_ICA.COD_PROFESOR, PROFESORI_ICA.NUME_P, PROFESORI_ICA.PRENUME_P, DEPARTAMENTE_ICA.COD_DEP
FROM PROFESORI_ICA, DEPARTAMENTE_ICA
WHERE DEPARTAMENTE_ICA.COD_DEP=PROFESORI_ICA.COD_DEP

/*13. Sa se afiseze notele la examenul din data 12.01.2018.*/
SELECT STUDENTI_ICA.NR_MATRICOL, STUDENTI_ICA.NUME, STUDENTI_ICA.PRENUME, EXAMENE_ICA.NOTA
FROM STUDENTI_ICA, EXAMENE_ICA
WHERE STUDENTI_ICA.NR_MATRICOL=EXAMENE_ICA.NR_MATRICOL AND EXAMENE_ICA.DATA='01/12/2018';

/*14. Sa se afiseze materia, profesorul care o preda, tipul departamentului precum si sala.*/
SELECT DISTINCT MATERII_ICA.DENUMIRE, PROFESORI_ICA.NUME_P, PROFESORI_ICA.PRENUME_P, DEPARTAMENTE_ICA.TIP, DEPARTAMENTE_ICA.SALA
FROM PROFESORI_ICA
INNER JOIN DEPARTAMENTE_ICA ON DEPARTAMENTE_ICA.COD_DEP = PROFESORI_ICA.COD_DEP
INNER JOIN MATERII_ICA ON MATERII_ICA.COD_MATERIE = PROFESORI_ICA.COD_MATERIE

/*15. Sa se ordoneze studentii in ordine alfabetica.*/
SELECT s.NR_MATRICOL, s.NUME, s.PRENUME, b.TIP_BURSA, b.VALOARE
FROM BURSE_ICA b, STUDENTI_ICA s
WHERE b.COD_BURSA=s.COD_BURSA
ORDER BY s.NUME, s.PRENUME
